# Generated by Django 4.2.11 on 2024-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.PositiveIntegerField()),
                ('information', models.TextField()),
                ('img', models.ImageField(blank=True, default='noImage.png', upload_to='')),
            ],
        ),
    ]
