# Generated by Django 4.2.11 on 2024-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='postal_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='郵便番号'),
        ),
    ]
