# Generated by Django 4.2.11 on 2024-07-29 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default='21:00:00', verbose_name='閉店時間'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_friday',
            field=models.BooleanField(default=False, verbose_name='金曜定休'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_monday',
            field=models.BooleanField(default=False, verbose_name='月曜定休'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_saturday',
            field=models.BooleanField(default=False, verbose_name='土曜定休'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_sunday',
            field=models.BooleanField(default=False, verbose_name='日曜定休'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_thursday',
            field=models.BooleanField(default=False, verbose_name='木曜定休'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_tuesday',
            field=models.BooleanField(default=False, verbose_name='火曜定休'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_wednesday',
            field=models.BooleanField(default=False, verbose_name='水曜定休'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(default='09:00:00', verbose_name='開店時間'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(default=2, max_length=200, verbose_name='店舗名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='budget',
            field=models.PositiveIntegerField(verbose_name='予算'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='店舗画像'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='information',
            field=models.TextField(verbose_name='店舗説明'),
        ),
    ]
