# Generated by Django 4.2.11 on 2024-07-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0002_category_remove_restaurant_name_restaurant_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
