# Generated by Django 4.2.11 on 2024-07-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_delete_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200, verbose_name='店舗名')),
                ('budget', models.PositiveIntegerField(verbose_name='予算')),
                ('information', models.TextField(verbose_name='店舗説明')),
                ('img', models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='店舗画像')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('open_time', models.TimeField(default='09:00:00', verbose_name='開店時間')),
                ('close_time', models.TimeField(default='21:00:00', verbose_name='閉店時間')),
                ('closed_monday', models.BooleanField(default=False, verbose_name='月曜定休')),
                ('closed_tuesday', models.BooleanField(default=False, verbose_name='火曜定休')),
                ('closed_wednesday', models.BooleanField(default=False, verbose_name='水曜定休')),
                ('closed_thursday', models.BooleanField(default=False, verbose_name='木曜定休')),
                ('closed_friday', models.BooleanField(default=False, verbose_name='金曜定休')),
                ('closed_saturday', models.BooleanField(default=False, verbose_name='土曜定休')),
                ('closed_sunday', models.BooleanField(default=False, verbose_name='日曜定休')),
            ],
        ),
    ]
