# Generated by Django 4.2.11 on 2024-09-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_customuser_stripe_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='media_local/noImage.png', upload_to='', verbose_name='店舗画像'),
        ),
    ]
