# Generated by Django 4.2.11 on 2024-09-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0004_alter_restaurant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='店舗画像'),
        ),
    ]
