# Generated by Django 4.2.11 on 2024-07-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0005_restaurant_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
