# Generated by Django 4.2.11 on 2024-09-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='restaurant_name',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('restaurant', 'user')},
        ),
    ]
