# Generated by Django 4.2.11 on 2024-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0007_rename_restaurant_name_review_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_restaurant',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.restaurant', verbose_name='お気に入りの店舗'),
        ),
    ]
