# Generated by Django 4.2.11 on 2024-09-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0009_remove_customuser_favorite_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='favorite_restaurant',
        ),
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='update_date',
        ),
    ]
