# Generated by Django 4.2.11 on 2024-09-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0011_restaurantbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbooking',
            name='people_number',
            field=models.PositiveIntegerField(verbose_name='予約人数'),
        ),
    ]
