# Generated by Django 4.2.11 on 2024-09-24 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0012_alter_restaurantbooking_people_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbooking',
            name='people_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='予約人数'),
        ),
    ]
